### ISSUE TITLE
500 (Internal Server Error) on register

### ISSUE THREAD

**Issue by iHxFall** [sant0ro/espreso#23]
When I try to register, I check the captcha, but it says that I did not check:
http://i.imgur.com/X4ulcZm.png // register error
http://i.imgur.com/ZS5btIs.png // Internal Server Error

I already imported the artisan file to my database
I tested with captcha of 2 different accounts
I tested with 2 different versions of chocolatey

Sorry for my bad english,I'm brazilian

**Comment by sant0ro** [comment]
No prob, I'd speak portuguese if you prefer.

Did you created an account on Google Recapthca and set on Chocolatey configuration files?

**Comment by ovflowd** [comment]
Espreso Isn't ready for production/development usage.

It's under development and unusable.

**Comment by ovflowd** [comment]
And you created the Issue in wrong place. Here is the Espreso Repository, not the Chocolatey repository.

Please create your Issue here: https://github.com/sant0ro/chocolatey/issues
