### ISSUE TITLE
Readme installation missing file?

### ISSUE THREAD

**Issue by dhalucario** [sant0ro/espreso#25]
Hey, after finally being done with installing chocolatey I would love to install espreso, but I cant find the espreso.php in the config folder like the tutorial says. Is there something I'm missing? Also can I install espreso into the same www folder as my current chocolatey installation or do I need to setup a second vhost in my apache?

**Comment by ovflowd** [comment]
Espreso isn't ready to be used. It's under development and unstable.

**Comment by dhalucario** [comment]
Is there any alternative I could use?

**Comment by ovflowd** [comment]
Sadly, Chocolatey doesn't have yet an usable Housekeeping. I'm really sorry for this, But as it's stated, Chocolatey it's under development and under Alpha Releases, going now to Beta Releases.

Housekeeping will be introduced in some weeks.

**Comment by dhalucario** [comment]
Alright. Dont worry, I can wait. I'm really thankful that you are working on this
