### ISSUE TITLE
New developer on Espreso

### ISSUE THREAD

**Issue by dotmbf** [sant0ro/espreso#26]
Took a look through Espreso, does anyone have an idea why @Emeto chose to create new users for administrators? This seems like an odd idea to me..

**Comment by ovflowd** [comment]
It's likely Habbo works.

You separate Habbo accounts actually from Housekeeping accounts.

So if you have the password of his Chocolatey login, you wouldn't have from his Espresso login that maybe will be with other Username. (in thesis).

**Comment by dotmbf** [comment]
Ah, sure, I'll continue doing it this way then. Thanks
