### ISSUE TITLE
Please, response

### ISSUE THREAD

**Issue by AlexJey** [sant0ro/espreso#27]
Hi,
please post the web.config for IIS!
with the config for server.php and other!

**Comment by ovflowd** [comment]
The `web.config` is available on the `public/` folder.

**Comment by AlexJey** [comment]
For iis, is not valid, is for the /

**Comment by ovflowd** [comment]
You need configure the `DocumentRoot` on IIS to `public/` folder.

You can change this opening `IIS Manager` > `Default Website` > `Basic Settings` and change the Directory from `C:/inetpub/wwwroot/` to `C:/inetpub/wwwroot/public`
