### ISSUE TITLE
Espresso migrate error

### ISSUE THREAD

**Issue by T0niiiiii** [sant0ro/espreso#30]
I get error when I try migrate database with command: php artisan migrate

PHP Warning:  require(/var/www/espresso.onnelahotelli.com/public_html/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/espresso.onnelahotelli.com/public_html/bootstrap/autoload.php on line 17
PHP Fatal error:  require(): Failed opening required '/var/www/espresso.onnelahotelli.com/public_html/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/espresso.onnelahotelli.com/public_html/bootstrap/autoload.php on line 17

**Comment by ovflowd** [comment]
I think you didn't traded what it's written on this repository...

Just go back to github.com/sant0ro/espresso and read the big letters saying that espresso isn't ready to be used.

Thanks.
