### ISSUE TITLE
Project avancement ?

### ISSUE THREAD

**Issue by odrik** [sant0ro/espreso#31]
The project is stopped ?

**Comment by TheOmanNorge** [comment]
Not as I know about. 

I recommend you to follow this thread. 
https://github.com/sant0ro/chocolatey/issues/258

> Chocolatey 3.0 public version will be released in January of 2018. And the official version in the end of January 2018, when everyone test the 3.0 version and report the bugs.

Not sure if there has been any change in plans or if this version will include Espresso. 
But time will tell. 😃

**Comment by ovflowd** [comment]
Hey! Espresso will be continued after I finished all the changes of the Chocolatey 3 road map for Chocolatey.

I'm already working in Chocolatey, first commits expected to be released this weekend.

Seeya! 😄
